language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Rmom96OzBTEbiGC53hArgnI1Q2rB3Dj1axp3Bnm03GMRqBzwyxeI8djkmqbE5LY4brgAURt2XXAuvx44j30AuQaUL3sWdgzCeNbUgXpU+H8ENzuyGqrmx16I5BRAUJjHwAb/Yw38s+jTBWkzIuH3oKGJrjcBBQOIVyu8YQtxkJ4nV8QAmk/ldSmaeTuyPu3Ct4C9ZAgJN8ioyKQlEReJB3oja0rPWqVqAaE9muRDvjQYGm5F6b5+1sGlJ0h3eeTBkvYeD7AuDU5iebYWnLf0HhSdnwnMztX7reqssGnPxe+L3dQYA3HwlKxz+nLTE3Dd1tNFNUVchFaj94L+p3Pay0TogX6UtjCCdMqmSiPULFgMn1sJNBLbmvsCAQhIWJ482HOguSo8qz3gleLIEvNSTTqJQecqjAhy8LGZsIfv1+Hiqg1EbEsGW2KlUT0kfSD4K24O+3pV0gFWakyq/FXH170d96i9+gw1ufJSJ2FzMKTXWf+d6GuBOBLFPupA5cFTzqbsBaUYQTrCy9EELY9knYwS/o5wfeRdq/6cwIQpyACmgfzzmGkfgcsqAB4Wmr9jvTyGzGuPSbQCtKsh2jN8RF7eJFr0MRBk+T9K/S/ONe6BIuTA+Iaaj+2KPIQbDfDtMSpXI4Z+zUePRy+Ir6LwBLYSEpd1zqqHnZrWCCz9ksc=
  app: protected-beach-88016
  on:
    repo: JNighs/blog-app-mongoose-challenge-solution
