language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: cfvFeNyFkwN/NwA5zfIql6HUIHPMrulvWnSxTKJfv162U3I3Hrpa3nP8li0ehQHYFDMRoETeouOSJt4iEoW8NLIiVTEtSRndW4Tr3vMm2SNXzmz7y2VPO6ddPsC0CiW2Am4cDVBZhn2fz27usfa4KS4FhBXLmuFd2B19AmrAjE+WfIefYhxYw+qyACquR2gbE5h+kFGS4g30tuq4BkGsg8v5j4NpIRiA+aSCTMpGJd/WaFEXEABBhuG92chdDYOI/XQd/vOLQzbISoNnnPG1LSrk7SxbMQ7o4nbHxJDGNMQvzWykTEmxAU+pMGkSevF7ewBOdgYQT+mIkpvkCpr5lXNDC4Pr2uJZBm/8tKZI4XeDoXGtyomhOruJDp/UGPc6ecSGnGQ/A097sufPyC8ujtQtDwYTb9+ys8/BkspUN4MKEAT8JXzDEBfxnnkPA3skKvXPybW3YKmnI/l3DHOW/UcYUxawuxrRRG6dzGiDNBPFBiihGe2CIoPOXnTpsKhvZnRj2pLOKuJjck3waac8+aqpa7wHJ6OhVSISJ5GoZ56V1qt8fE42nvpaIPtVRzycetUXD1a9q1RiYtfo15Kd4p1DWvZ2MzKD4T852dkRFQXQy0uoyT+D2eNGf+WqM+SK7ROe7w2eTCQVpJ2Ibus1BKpPq85XO6owM/cK+qzK180=
  app: protected-beach-88016
  on:
    repo: JNighs/blog-app-mongoose-challenge-solution
